services:
    
    blast.resource_registry:
         class: Blast\Bundle\ResourceBundle\Metadata\MetadataRegistry
         
    blast.doctrine.orm.listener.mapped_superclass:
        class: Blast\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber
        arguments: ['@blast.resource_registry']
        tags:
            - { name: doctrine.event_subscriber, priority: 1000}
            
    blast.doctrine.orm.naming_strategy.underscored_bundle_prefix:
        class: Blast\Bundle\ResourceBundle\NamingStrategy\ORMUnderscoredBundlePrefixStrategy
        arguments: ['%kernel.bundles%']
        
        
    
    
   # blast.sonata.crud_controller:
   #     class:  Blast\Bundle\ResourceBundle\Sonata\Controller\CRUDController
   #     calls:
   #         - ["setContainer", ['@service_container']]
            
     
   # sonata.admin.helper:
   #     class:  Blast\Bundle\ResourceBundle\Sonata\Admin\AdminHelper
   #     arguments: ['@sonata.admin.pool']