services:
    
    blast.resource.resource_registry:
         class: Blast\Bundle\ResourceBundle\Metadata\MetadataRegistry
         
    blast.resource.doctrine.orm.listener.mapped_superclass:
        class: Blast\Bundle\ResourceBundle\Doctrine\ORM\EventListener\MappedSuperClassSubscriber
        arguments: ['@blast.resource.resource_registry']
        tags:
            - { name: doctrine.event_subscriber, priority: 1000}
            
    blast.resource.doctrine.orm.naming_strategy.underscored_bundle_prefix:
        class: Blast\Bundle\ResourceBundle\Doctrine\ORM\NamingStrategy\UnderscoredBundlePrefixStrategy
        arguments: ['%kernel.bundles%']
        
    blast.resource.sonata.label_strategy.prefix:
        class: Blast\Bundle\ResourceBundle\Sonata\Translator\PrefixLabelTranslatorStrategy
        shared: false
    
    
   # blast.sonata.crud_controller:
   #     class:  Blast\Bundle\ResourceBundle\Sonata\Controller\CRUDController
   #     calls:
   #         - ["setContainer", ['@service_container']]
            
     
   # sonata.admin.helper:
   #     class:  Blast\Bundle\ResourceBundle\Sonata\Admin\AdminHelper
   #     arguments: ['@sonata.admin.pool']